services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: mydb 
    ports: 
      - "5432:5432" 
    volumes: 
      - ./pgdata:/var/lib/postgresql/data/pgdata 

  pgadmin: 
    image: dpage/pgadmin4 
    container_name: pgadmin 
    restart: always 
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports: 
      - "8080:80" 
    depends_on: 
      - db 


  app: 
    build: ./app 
    depends_on: 
      - db 
    environment: 
      DB_HOST: db
      DB_PORT: 5432 
      DB_USER: postgres
      DB_PASSWORD: 1234 
      DB_NAME: mydb
    ports: 
      - "8000:8000" 
    restart: unless-stopped 
    command: python main.py init

volumes: 
  db_data: