# 使用輕量級 Python 基底映像
FROM python:3.11-slim

# 設定工作目錄
WORKDIR /app


# 複製 requirements.txt 並安裝依賴
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 複製應用程式原始碼
COPY . .

# 預設啟動指令
CMD ["python", "main.py"]